### ISSUE TITLE
Login step 2 failed

### ISSUE THREAD

**Issue by P6g9YHK6** [Maxmudjon/Get_MiHome_devices_token#3]
Error on sign-in "Login step 2 failed"

**Comment by Maxmudjon** [comment]
login or password wrong

**Comment by Canis1Majoris** [comment]
Triple checked password but still getting this error

**Comment by Maxmudjon** [comment]
Maybe there is a VPN connection?

**Comment by andershf** [comment]
I got the same error. 
I then closed the app, ran it as administrator, and it worked.

**Comment by flixlix** [comment]
I tried running it as admin and it didn't work

**Comment by msedv** [comment]
Same here, even as admin

**Comment by UraniumDonut** [comment]
same here, even as admin

**Comment by Bruteforce150** [comment]
If you are using a phone number to log in, you'll enter it in full length, with the country code (e.g. +71234567890). It work's for me.

**Comment by iAmRenzo** [comment]
I have the same problem. Probably the 2FA setup. When loggin in on the site there is a code mailed to me.

**Comment by poldim** [comment]
![image](https://user-images.githubusercontent.com/16869713/125543885-ebaae8e5-c333-498a-9b61-fdcbc55fc738.png)

**Comment by vagprogrammer** [comment]
I first opened the official app, and logged in, the app requested me a phone number, after that I was able to login using this app.

**Comment by LemarinelNet** [comment]
Had the same issue. 
Here is how I solved it : 
First, I was using roborock application, where I created an account. 
With this account, the app returned me a "Login step 2 failed".

Then I installed Xiaomi Home application, and re-paired the robot with the xiaomi home app.
I then used this app to get token (still with xiaomi home login !) and it worked !

**Comment by Daneild** [comment]
Login step 2 failed  with no workaround

**Comment by 9sang** [comment]
Login xiaomi official website can solve

**Comment by MiralDesai** [comment]
Tried the above but I don't think it works anymore, anyone else able to confirm?

**Comment by QuadNL** [comment]
> Tried the above but I don't think it works anymore, anyone else able to confirm?

Yup, same for me, differtent IPs, different networks and devices, all the same error.
First login to the website and then trying the app doesn't work.

**Comment by aldaja** [comment]
https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor
