### ISSUE TITLE
1.0.3 Not working on M1

### ISSUE THREAD

**Issue by aiblis** [Maxmudjon/Get_MiHome_devices_token#5]
Hey!

While 1.0.2 works perfectly on my M1 Mac Mini, this release just goes on and on with the following message:

![image](https://user-images.githubusercontent.com/12009164/126074460-5eab7694-40b9-4ed7-b36e-b7d0bf9a2c71.png)

I am unable to open it Gatekeeper friendly as with 1.0.2, don't know why... 

If you want further info that I can help you with just let me know :)

Thanks!

**Comment by KyrreP** [comment]
Hello! Same issue. 1.0.2 works on my M1.

**Comment by Maxmudjon** [comment]
realese (1.0.3 for M1) deleted
